### ISSUE TITLE
On-board LEDs

### ISSUE THREAD

**Issue by elf55** [LilyGO/TTGO-T8-ESP32#1]
There are at least 3 on-board LEDs.  Is there documentation on how they are connected to GPIO pins?

**Comment by LilyGO** [comment]
One is a power light, and the other is an LED foot controlled by the GPIO21 pin.

**Comment by LilyGO** [comment]
If you need it, we can send you a T8 schematic

**Comment by amirgon** [comment]
What would happen to the power light during deep-sleep? Would it still be on?

**Comment by elf55** [comment]
A schematic would solve all questions, but knowing what the LEDs are connected to helps immediately.

**Comment by pilnikov** [comment]
I need a schematic too
gpio 16, 17 where?

**Comment by remedix** [comment]
Can you please explain how to turn off these LEDs ? There is one blinking LED and one constant on LED

**Comment by pilnikov** [comment]
just unsolder

**Comment by johndoesenior** [comment]
I need the schematic also.
I cant find TX2,RX2 in the pinout
