### ISSUE TITLE
TTGO T8 V1.7 cannot be powered on from the battery

### ISSUE THREAD

**Issue by dukeduck1984** [LilyGO/TTGO-T8-ESP32#10]
Hi,

I recently bought 2 TTGO T8 V1.7 boards, neither can be powered on from a 18650 battery (fully charged, voltage measured 4.3V).  I also have a T8 V1.3 which works properly with the very same battery.

Any idea what can go wrong?

Thanks.

**Comment by mattsmithuk** [comment]
Can I ask what the issue was? I am having a similar issue
